# Generated by Django 5.0.4 on 2024-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tambahProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga', models.FloatField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='product_pics')),
                ('slug', models.SlugField(unique=True)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
