# Generated by Django 5.0.4 on 2024-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_tambahproduk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tambahproduk',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
    ]
