# Generated by Django 5.0.4 on 2024-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tambahproduk_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='order_images')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='tambahproduk',
            name='gambar',
            field=models.ImageField(upload_to='product'),
        ),
    ]
